package com.lin.shop.mapper;

import com.lin.shop.pojo.TradeUserMoneyLog;
import com.lin.shop.pojo.TradeUserMoneyLogExample;
import com.lin.shop.pojo.TradeUserMoneyLogKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TradeUserMoneyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int countByExample(TradeUserMoneyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int deleteByExample(TradeUserMoneyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int deleteByPrimaryKey(TradeUserMoneyLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int insert(TradeUserMoneyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int insertSelective(TradeUserMoneyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    List<TradeUserMoneyLog> selectByExample(TradeUserMoneyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    TradeUserMoneyLog selectByPrimaryKey(TradeUserMoneyLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") TradeUserMoneyLog record, @Param("example") TradeUserMoneyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int updateByExample(@Param("record") TradeUserMoneyLog record, @Param("example") TradeUserMoneyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int updateByPrimaryKeySelective(TradeUserMoneyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int updateByPrimaryKey(TradeUserMoneyLog record);
}