package com.lin.shop.mapper;

import com.lin.shop.pojo.TradeUser;
import com.lin.shop.pojo.TradeUserExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TradeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int countByExample(TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int deleteByExample(TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int insert(TradeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int insertSelective(TradeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    List<TradeUser> selectByExample(TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    TradeUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") TradeUser record, @Param("example") TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int updateByExample(@Param("record") TradeUser record, @Param("example") TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int updateByPrimaryKeySelective(TradeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbggenerated Thu Feb 13 20:39:46 CST 2020
     */
    int updateByPrimaryKey(TradeUser record);
}